### ISSUE TITLE
Request for data provision in each object of the T-LESS data set generated by render_codebook.py

### ISSUE THREAD

**Issue by Asei-3** [fylwen/EEGP-AAE#1]
Hello.
Thank you for proposing this wonderful method and releasing the code.
I'm trying to run your public code render_codebook.py.
However, in our execution environment, the following error or "Backend not available" occurred and we could not run the program correctly.

`Creating embedding .. [w] b'GLX: No GLXFBConfigs returned'232 ] | | (ETA: --:--:--) [w] b'GLX: Failed to find a suitable GLXFBConfig' [x] Window creation failed`

The above error may be caused by a problem in our execution environment, but we cannot find a solution.
If possible, could you please provide me with the embedded images and npz files of each Object1-30 generated by render_codebook.py for the T-LESS dataset?
I’m sorry for the trouble. Thank you so much.

**Comment by fylwen** [comment]
Hi, thanks for your interest in this work. 

The embedded images, as well as their corresponding 2D bounding boxes and rotations could be found in the following link:

https://drive.google.com/drive/folders/1RZGjmvQnQpH8TW2giIvDDpg5MRbPGPEP?usp=sharing

Furthermore, if necessary, you need to generate the corresponding edge maps with Canny (as described in Line76 of render_codebook.py).

Hope the information helps, and sorry for the late reply.

Best regards,
Yilin

**Comment by Asei-3** [comment]
Hello, thanks for the reply.
We appreciate your help in resolving the problem.
And thank you for your kind attention.
I was able to verify the data you shared.

Best regards,
Asei
