### ISSUE TITLE
Unable to retrieve data from the URL

### ISSUE THREAD

**Issue by Arka161** [fylwen/EEGP-AAE#2]
Hello there, 

The Google Drive URL linking us to the pre-trained models and the demo data does not work anymore (the one in the `README.md`). Could you please provide a fresh URL? 

Appreciate the help. 

Thank you

**Comment by fylwen** [comment]
Hi, thanks for letting me know. The URL in Readme has been updated.

Hope this helps!

**Comment by Arka161** [comment]
Thank you for your help!
